// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-03-02 16:48:23
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// SysUser is the golang structure of table sys_user for DAO operations like Where/Data.
type SysUser struct {
	g.Meta        `orm:"table:sys_user, do:true"`
	Id            interface{}
	UserName      interface{}
	Mobile        interface{}
	UserNickname  interface{}
	Birthday      interface{}
	UserPassword  interface{}
	UserSalt      interface{}
	UserStatus    interface{}
	UserEmail     interface{}
	GoogleSecret  interface{}
	GoogleStatus  interface{}
	Sex           interface{}
	Avatar        interface{}
	DeptId        interface{}
	Remark        interface{}
	IsAdmin       interface{}
	Address       interface{}
	Describe      interface{}
	LastLoginIp   interface{}
	LastLoginTime *gtime.Time
	CreatedAt     *gtime.Time
	UpdatedAt     *gtime.Time
	DeletedAt     *gtime.Time
}
