ALTER TABLE cs_tenant COMMENT = '租户表';
ALTER TABLE cs_tenant
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  MODIFY COLUMN tenant_id VARCHAR(64) NOT NULL COMMENT '租户ID',
  MODIFY COLUMN name VARCHAR(128) NOT NULL COMMENT '租户名称',
  MODIFY COLUMN status VARCHAR(32) NOT NULL DEFAULT 'enabled' COMMENT '租户状态：enabled启用，disabled禁用',
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  MODIFY COLUMN deleted_at DATETIME NULL COMMENT '删除时间，空表示未删除';

ALTER TABLE cs_channel COMMENT = '渠道表';
ALTER TABLE cs_channel
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  MODIFY COLUMN tenant_id VARCHAR(64) NOT NULL COMMENT '租户ID',
  MODIFY COLUMN app_id VARCHAR(64) NOT NULL DEFAULT 'default' COMMENT '应用ID',
  MODIFY COLUMN channel_type VARCHAR(32) NOT NULL COMMENT '渠道类型：web、h5、app、wechat等',
  MODIFY COLUMN channel_name VARCHAR(128) NOT NULL COMMENT '渠道名称',
  MODIFY COLUMN app_key VARCHAR(128) NOT NULL COMMENT '渠道接入Key',
  MODIFY COLUMN secret VARCHAR(255) NOT NULL COMMENT '渠道接入密钥',
  MODIFY COLUMN default_group_id VARCHAR(64) NOT NULL DEFAULT '' COMMENT '默认坐席组ID，用于渠道进线时默认分配',
  MODIFY COLUMN status VARCHAR(32) NOT NULL DEFAULT 'enabled' COMMENT '渠道状态：enabled启用，disabled禁用',
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  MODIFY COLUMN deleted_at DATETIME NULL COMMENT '删除时间，空表示未删除';

ALTER TABLE cs_user COMMENT = '客户用户表';
ALTER TABLE cs_user
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  MODIFY COLUMN tenant_id VARCHAR(64) NOT NULL COMMENT '租户ID',
  MODIFY COLUMN app_id VARCHAR(64) NOT NULL DEFAULT 'default' COMMENT '应用ID',
  MODIFY COLUMN user_id VARCHAR(64) NOT NULL COMMENT '客户用户ID',
  MODIFY COLUMN nickname VARCHAR(128) NOT NULL DEFAULT '' COMMENT '客户昵称',
  MODIFY COLUMN avatar VARCHAR(512) NOT NULL DEFAULT '' COMMENT '客户头像地址',
  MODIFY COLUMN phone VARCHAR(32) NOT NULL DEFAULT '' COMMENT '客户手机号',
  MODIFY COLUMN email VARCHAR(128) NOT NULL DEFAULT '' COMMENT '客户邮箱',
  MODIFY COLUMN level VARCHAR(32) NOT NULL DEFAULT 'normal' COMMENT '客户等级：normal普通，vip贵宾等',
  MODIFY COLUMN status VARCHAR(32) NOT NULL DEFAULT 'enabled' COMMENT '客户状态：enabled启用，disabled禁用',
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  MODIFY COLUMN deleted_at DATETIME NULL COMMENT '删除时间，空表示未删除';

ALTER TABLE cs_agent COMMENT = '客服坐席表';
ALTER TABLE cs_agent
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  MODIFY COLUMN tenant_id VARCHAR(64) NOT NULL COMMENT '租户ID',
  MODIFY COLUMN agent_id VARCHAR(64) NOT NULL COMMENT '坐席ID',
  MODIFY COLUMN username VARCHAR(128) NOT NULL COMMENT '坐席登录账号',
  MODIFY COLUMN display_name VARCHAR(128) NOT NULL COMMENT '坐席显示名称',
  MODIFY COLUMN max_sessions INT NOT NULL DEFAULT 5 COMMENT '最大同时接待会话数',
  MODIFY COLUMN status VARCHAR(32) NOT NULL DEFAULT 'enabled' COMMENT '坐席状态：enabled启用，disabled禁用',
  MODIFY COLUMN online_status VARCHAR(32) NOT NULL DEFAULT 'offline' COMMENT '在线状态：online在线，offline离线，busy忙碌',
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  MODIFY COLUMN deleted_at DATETIME NULL COMMENT '删除时间，空表示未删除';

ALTER TABLE cs_agent_group COMMENT = '客服坐席组表';
ALTER TABLE cs_agent_group
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  MODIFY COLUMN tenant_id VARCHAR(64) NOT NULL COMMENT '租户ID',
  MODIFY COLUMN group_id VARCHAR(64) NOT NULL COMMENT '坐席组ID',
  MODIFY COLUMN name VARCHAR(128) NOT NULL COMMENT '坐席组名称',
  MODIFY COLUMN status VARCHAR(32) NOT NULL DEFAULT 'enabled' COMMENT '坐席组状态：enabled启用，disabled禁用',
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  MODIFY COLUMN deleted_at DATETIME NULL COMMENT '删除时间，空表示未删除';

ALTER TABLE cs_agent_group_rel COMMENT = '坐席与坐席组关系表';
ALTER TABLE cs_agent_group_rel
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  MODIFY COLUMN tenant_id VARCHAR(64) NOT NULL COMMENT '租户ID',
  MODIFY COLUMN agent_id VARCHAR(64) NOT NULL COMMENT '坐席ID',
  MODIFY COLUMN group_id VARCHAR(64) NOT NULL COMMENT '坐席组ID',
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE cs_session COMMENT = '客服会话表';
ALTER TABLE cs_session
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  MODIFY COLUMN tenant_id VARCHAR(64) NOT NULL COMMENT '租户ID',
  MODIFY COLUMN app_id VARCHAR(64) NOT NULL DEFAULT 'default' COMMENT '应用ID',
  MODIFY COLUMN session_id VARCHAR(64) NOT NULL COMMENT '会话ID',
  MODIFY COLUMN channel_id VARCHAR(64) NOT NULL DEFAULT '' COMMENT '渠道ID或渠道接入Key',
  MODIFY COLUMN user_id VARCHAR(64) NOT NULL COMMENT '客户用户ID',
  MODIFY COLUMN agent_id VARCHAR(64) NOT NULL DEFAULT '' COMMENT '当前接待坐席ID',
  MODIFY COLUMN group_id VARCHAR(64) NOT NULL DEFAULT '' COMMENT '当前分配坐席组ID',
  MODIFY COLUMN status VARCHAR(32) NOT NULL COMMENT '会话状态：waiting等待中，serving服务中，closed已关闭等',
  MODIFY COLUMN priority INT NOT NULL DEFAULT 0 COMMENT '会话优先级，数值越大优先级越高',
  MODIFY COLUMN last_seq BIGINT NOT NULL DEFAULT 0 COMMENT '会话最新消息序号',
  MODIFY COLUMN user_read_seq BIGINT NOT NULL DEFAULT 0 COMMENT '客户已读消息序号',
  MODIFY COLUMN agent_read_seq BIGINT NOT NULL DEFAULT 0 COMMENT '坐席已读消息序号',
  MODIFY COLUMN last_msg_time DATETIME NULL COMMENT '最后一条消息时间',
  MODIFY COLUMN source_ip VARCHAR(64) NOT NULL DEFAULT '' COMMENT '客户来源IP',
  MODIFY COLUMN user_agent VARCHAR(512) NOT NULL DEFAULT '' COMMENT '客户浏览器或客户端标识',
  MODIFY COLUMN login_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '客户进入会话时间',
  MODIFY COLUMN close_time DATETIME NULL COMMENT '会话关闭时间',
  MODIFY COLUMN close_reason VARCHAR(255) NOT NULL DEFAULT '' COMMENT '会话关闭原因',
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  MODIFY COLUMN deleted_at DATETIME NULL COMMENT '删除时间，空表示未删除';

ALTER TABLE cs_message COMMENT = '聊天消息表';
ALTER TABLE cs_message
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  MODIFY COLUMN tenant_id VARCHAR(64) NOT NULL COMMENT '租户ID',
  MODIFY COLUMN app_id VARCHAR(64) NOT NULL DEFAULT 'default' COMMENT '应用ID',
  MODIFY COLUMN channel_id VARCHAR(64) NOT NULL DEFAULT '' COMMENT '渠道ID或渠道接入Key',
  MODIFY COLUMN msg_id VARCHAR(64) NOT NULL COMMENT '消息ID',
  MODIFY COLUMN session_id VARCHAR(64) NOT NULL COMMENT '会话ID',
  MODIFY COLUMN client_msg_id VARCHAR(128) NOT NULL COMMENT '客户端消息ID，用于幂等去重',
  MODIFY COLUMN sender_id VARCHAR(64) NOT NULL COMMENT '发送方ID',
  MODIFY COLUMN sender_type VARCHAR(32) NOT NULL COMMENT '发送方类型：customer客户，agent坐席，system系统',
  MODIFY COLUMN receiver_id VARCHAR(64) NOT NULL DEFAULT '' COMMENT '接收方ID',
  MODIFY COLUMN msg_type VARCHAR(32) NOT NULL DEFAULT 'text' COMMENT '消息类型：text文本，image图片，file文件等',
  MODIFY COLUMN content TEXT NOT NULL COMMENT '消息内容',
  MODIFY COLUMN seq BIGINT NOT NULL COMMENT '会话内消息序号',
  MODIFY COLUMN status VARCHAR(32) NOT NULL DEFAULT 'sent' COMMENT '消息状态：sending发送中，sent已发送，read已读，failed失败等',
  MODIFY COLUMN send_time DATETIME NOT NULL COMMENT '发送时间',
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN deleted_at DATETIME NULL COMMENT '删除时间，空表示未删除';

ALTER TABLE cs_outbox COMMENT = '消息事务发件箱表';
ALTER TABLE cs_outbox
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  MODIFY COLUMN tenant_id VARCHAR(64) NOT NULL COMMENT '租户ID',
  MODIFY COLUMN aggregate_type VARCHAR(64) NOT NULL COMMENT '聚合类型，如message、session',
  MODIFY COLUMN aggregate_id VARCHAR(64) NOT NULL COMMENT '聚合ID',
  MODIFY COLUMN event_type VARCHAR(64) NOT NULL COMMENT '事件类型',
  MODIFY COLUMN payload JSON NOT NULL COMMENT '事件载荷JSON',
  MODIFY COLUMN status VARCHAR(32) NOT NULL DEFAULT 'pending' COMMENT '投递状态：pending待投递，sent已投递，retry重试中，failed失败',
  MODIFY COLUMN retry_count INT NOT NULL DEFAULT 0 COMMENT '重试次数',
  MODIFY COLUMN next_retry_time DATETIME NULL COMMENT '下次重试时间',
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE cs_audit_log COMMENT = '审计日志表';
ALTER TABLE cs_audit_log
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  MODIFY COLUMN tenant_id VARCHAR(64) NOT NULL COMMENT '租户ID',
  MODIFY COLUMN operator_id VARCHAR(64) NOT NULL COMMENT '操作人ID',
  MODIFY COLUMN operator_type VARCHAR(32) NOT NULL COMMENT '操作人类型：admin管理员，agent坐席，system系统',
  MODIFY COLUMN action VARCHAR(64) NOT NULL COMMENT '操作动作',
  MODIFY COLUMN resource_type VARCHAR(64) NOT NULL COMMENT '资源类型',
  MODIFY COLUMN resource_id VARCHAR(64) NOT NULL COMMENT '资源ID',
  MODIFY COLUMN ip VARCHAR(64) NOT NULL DEFAULT '' COMMENT '操作IP',
  MODIFY COLUMN user_agent VARCHAR(512) NOT NULL DEFAULT '' COMMENT '浏览器或客户端标识',
  MODIFY COLUMN detail JSON NULL COMMENT '操作详情JSON',
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE cs_sensitive_word COMMENT = '敏感词表';
ALTER TABLE cs_sensitive_word
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  MODIFY COLUMN tenant_id VARCHAR(64) NOT NULL COMMENT '租户ID',
  MODIFY COLUMN word VARCHAR(128) NOT NULL COMMENT '敏感词内容',
  MODIFY COLUMN level VARCHAR(32) NOT NULL DEFAULT 'medium' COMMENT '风险等级：low低，medium中，high高',
  MODIFY COLUMN action VARCHAR(32) NOT NULL DEFAULT 'review' COMMENT '处理动作：review审核，block拦截，replace替换',
  MODIFY COLUMN status VARCHAR(32) NOT NULL DEFAULT 'enabled' COMMENT '状态：enabled启用，disabled禁用',
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  MODIFY COLUMN deleted_at DATETIME NULL COMMENT '删除时间，空表示未删除';

ALTER TABLE cs_blacklist COMMENT = '风控黑名单表';
ALTER TABLE cs_blacklist
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  MODIFY COLUMN tenant_id VARCHAR(64) NOT NULL COMMENT '租户ID',
  MODIFY COLUMN target_type VARCHAR(32) NOT NULL COMMENT '黑名单对象类型：user客户，ip地址，phone手机号等',
  MODIFY COLUMN target_value VARCHAR(128) NOT NULL COMMENT '黑名单对象值',
  MODIFY COLUMN reason VARCHAR(255) NOT NULL DEFAULT '' COMMENT '加入黑名单原因',
  MODIFY COLUMN status VARCHAR(32) NOT NULL DEFAULT 'enabled' COMMENT '状态：enabled启用，disabled禁用',
  MODIFY COLUMN expire_at DATETIME NULL COMMENT '过期时间，空表示长期有效',
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  MODIFY COLUMN deleted_at DATETIME NULL COMMENT '删除时间，空表示未删除';

ALTER TABLE cs_risk_event COMMENT = '风控事件表';
ALTER TABLE cs_risk_event
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  MODIFY COLUMN tenant_id VARCHAR(64) NOT NULL COMMENT '租户ID',
  MODIFY COLUMN event_type VARCHAR(64) NOT NULL COMMENT '风控事件类型',
  MODIFY COLUMN target_type VARCHAR(32) NOT NULL COMMENT '风控对象类型：user客户，ip地址，message消息等',
  MODIFY COLUMN target_value VARCHAR(128) NOT NULL COMMENT '风控对象值',
  MODIFY COLUMN level VARCHAR(32) NOT NULL DEFAULT 'medium' COMMENT '风险等级：low低，medium中，high高',
  MODIFY COLUMN description VARCHAR(512) NOT NULL DEFAULT '' COMMENT '事件描述',
  MODIFY COLUMN status VARCHAR(32) NOT NULL DEFAULT 'open' COMMENT '处理状态：open待处理，processing处理中，closed已关闭',
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE cs_config COMMENT = '租户系统配置表';
ALTER TABLE cs_config
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  MODIFY COLUMN tenant_id VARCHAR(64) NOT NULL COMMENT '租户ID',
  MODIFY COLUMN config_key VARCHAR(128) NOT NULL COMMENT '配置键',
  MODIFY COLUMN config_value TEXT NOT NULL COMMENT '配置值',
  MODIFY COLUMN value_type VARCHAR(32) NOT NULL DEFAULT 'string' COMMENT '配置值类型：string字符串，number数字，bool布尔，json对象',
  MODIFY COLUMN remark VARCHAR(255) NOT NULL DEFAULT '' COMMENT '配置说明',
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  MODIFY COLUMN deleted_at DATETIME NULL COMMENT '删除时间，空表示未删除';
