events {}

http {
  upstream customer_api {
    server customer-api:8080;
  }

  upstream customer_ws {
    server customer-ws:8081;
  }

  server {
    listen 80;

    location /api/ {
      proxy_pass http://customer_api;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /customer-api/ {
      proxy_pass http://customer_api/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      client_max_body_size 8m;
    }

    location /customer-ws/ {
      proxy_pass http://customer_ws;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Host $host;
      proxy_read_timeout 3600s;
      rewrite ^/customer-ws/(.*)$ /$1 break;
    }

    location /ws {
      proxy_pass http://customer_ws;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Host $host;
      proxy_read_timeout 3600s;
    }
  }
}
