api:
  addr: ":8082"

ws:
  addr: ":8081"

log:
  level: "info"
  mode: "dev"

mysql:
  dsn: "root:root@tcp(127.0.0.1:3306)/customer_service?charset=utf8mb4&parseTime=true&loc=Local"

redis:
  addr: "127.0.0.1:6379"
  password: "QAZ123"
  db: 5

rocketmq:
  name_servers:
    - "127.0.0.1:9876"
  group: "customer-service"

jwt:
  secret: "change-me"
  issuer: "customer-service"
